name: mishwar_shared
description: Shared API client for the MISHWAR Flutter applications.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.19.7
  firebase_core: ^2.32.0
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
